# Generated by Django 6.0.3 on 2026-04-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sets',
            name='set_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sets',
            name='weight_in_pounds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
