# Generated by Django 6.0.3 on 2026-04-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_sets_reps_sets_set_number_sets_weight_in_pounds'),
        ('workout_exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='workout_exercise_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workout_exercises.workout_exercises'),
        ),
    ]
